#import "../fragments/Inspections.gql"
#import "../fragments/Ratings.gql"
#import "../fragments/Responses.gql"
#import "../fragments/Rooms.gql"

query inspection($id: String) {
  inspection(id: $id) {
    ...InspectionAttributes 
    ratings {
      ...RatingAttributes
      room {
        ...RoomAttributes        
      }
      responses {
        ...ResponseAttributes
      }     
    }
  }
}

